ccgains_project/ccgains_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('crypto/', include('crypto.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

ccgains_project/crypto/urls.py
"""Handles URLs"""
from django.urls import path
from . import views

app_name = 'crypto'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('<coin_symbol>/', views.detail, name='detail'),
    path('<coin_symbol>/<coin_id>/edit', views.detail_edit, name='detail_edit'),
    path('<coin_symbol>/<coin_id>/delete', views.detail_delete, name='detail_delete'),
]

ccgains_project/crypto/models.py
"""Models, as Model in MVC-architecture"""
from decimal import Decimal
from django.db import models

class Cryptocoin(models.Model):
    """Attributes are not final yet, depends on API use"""
    symbol = models.CharField(max_length=4)
    price = models.DecimalField(max_digits=6, decimal_places=2, default=Decimal('0.00'))
    amount = models.DecimalField(max_digits=12, decimal_places=3, default=Decimal('0.000'))
    userid = models.IntegerField(default=1)
    def __str__(self):
        return self.symbol
        

ccgains_project/crypto/forms.py
"""Forms to allow user input to save to model"""
from django import forms
from .models import Cryptocoin

class CoinForm(forms.ModelForm):
    """Form for the Cryptocoin model"""
    class Meta:
        model = Cryptocoin
        fields = ('amount', 'price',)

ccgains_project/crypto/views.py
"""Views, as Controller in MVC-architecture"""
import decimal
import requests
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy, reverse
from django.views import generic
from .models import Cryptocoin
from .forms import CoinForm

def index(request):
    """Gets JSON data from API as context for index.html"""
    url_coins = 'https://chasing-coins.com/api/v1/top-coins/50'
    top_coin_list = requests.get(url_coins).json()
    url_market = 'https://chasing-coins.com/api/v1/std/marketcap'
    market_cap = requests.get(url_market).json()
    context = {
        'top_coin_list': top_coin_list,
        'market_cap': market_cap,
        }
    return render(request, 'crypto/index.html', context)

def detail(request, coin_symbol):
    """
    Gets JSON data from API depending on coin symbol
    that is retrieved from /crypto/urls.py
    """
    url_market = 'https://chasing-coins.com/api/v1/std/marketcap'
    market_cap = requests.get(url_market).json()
    url_stats = 'https://chasing-coins.com/api/v1/std/coin/' + coin_symbol
    url_logo = 'https://chasing-coins.com/api/v1/std/logo/' + coin_symbol
    url_highlow = 'https://chasing-coins.com/api/v1/std/highlow/' + coin_symbol
    coin_stats = requests.get(url_stats).json()
    coin_highlow = requests.get(url_highlow).json()
    # Filter all coins by the corresponding symbol, i.e. 'ETH' or 'BTC'
    user_coins = Cryptocoin.objects.filter(symbol=coin_symbol)
    # Calculate the sum of the user's coins
    sum_value = 0
    sum_value_current = 0
    sum_ath = 0
    sum_month_h = 0
    sum_month_l = 0
    for coins in user_coins:
        sum_value += (coins.amount * coins.price)
        sum_value_current += (coins.amount * decimal.Decimal(coin_stats['price']))
        sum_ath += (coins.amount * decimal.Decimal(coin_highlow['ath']['price_usd']))
        sum_month_h += (coins.amount * decimal.Decimal(coin_highlow['month_high']['price_usd']))
        sum_month_l += (coins.amount * decimal.Decimal(coin_highlow['month_low']['price_usd']))
    # To save input form if it was submitted
    if request.method == "POST":
        form = CoinForm(request.POST)
        if form.is_valid():
            coinform = form.save(commit=False)
            coinform.symbol = coin_symbol
            coinform.save()
            return HttpResponseRedirect(reverse("crypto:detail", args=(coin_symbol,)))
    else:
        form = CoinForm()
    # context sent to the detail.html template
    context = {
        'market_cap': market_cap,
        'coin_stats': coin_stats,
        'coin_logo': url_logo,
        'coin_symbol': coin_symbol,
        'user_coins': user_coins,
        'form': form,
        'sum_value': sum_value,
        'sum_value_current': sum_value_current,
        'sum_ath': sum_ath,
        'sum_month_h': sum_month_h,
        'sum_month_l': sum_month_l,
        }
    return render(request, 'crypto/detail.html', context)

def detail_edit(request, coin_symbol, coin_id):
    """Edit user coins"""
    user_coins = get_object_or_404(Cryptocoin, symbol=coin_symbol, id=coin_id)
    url_logo = 'https://chasing-coins.com/api/v1/std/logo/' + coin_symbol
    url_stats = 'https://chasing-coins.com/api/v1/std/coin/' + coin_symbol
    coin_stats = requests.get(url_stats).json()
    url_market = 'https://chasing-coins.com/api/v1/std/marketcap'
    market_cap = requests.get(url_market).json()
    if request.method == "POST":
        form = CoinForm(request.POST, instance=user_coins)
        if form.is_valid():
            coinform = form.save(commit=False)
            coinform.symbol = coin_symbol
            coinform.save()
            return HttpResponseRedirect(reverse("crypto:detail", args=(coin_symbol,)))
    else:
        form = CoinForm(instance=user_coins)
    context = {
        'form': form,
        'coin_logo': url_logo,
        'coin_symbol': coin_symbol,
        'market_cap': market_cap,
        'coin_stats': coin_stats,
    }
    return render(request, 'crypto/detail_edit.html', context)

def detail_delete(request, coin_symbol, coin_id):
    """Delete user coins"""
    user_coins = get_object_or_404(Cryptocoin, symbol=coin_symbol, id=coin_id)
    url_logo = 'https://chasing-coins.com/api/v1/std/logo/' + coin_symbol
    url_stats = 'https://chasing-coins.com/api/v1/std/coin/' + coin_symbol
    coin_stats = requests.get(url_stats).json()
    url_market = 'https://chasing-coins.com/api/v1/std/marketcap'
    market_cap = requests.get(url_market).json()
    if request.method == "POST":
        user_coins.delete()
        return HttpResponseRedirect(reverse("crypto:detail", args=(coin_symbol,)))
    context = {
        'coin_logo': url_logo,
        'coin_symbol': coin_symbol,
        'user_coins': user_coins,
        'market_cap': market_cap,
        'coin_stats': coin_stats,
    }
    return render(request, 'crypto/detail_delete.html', context)

class SignUp(generic.CreateView):
    """!comment missing"""
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'
        

ccgains_project/crypto/templates/base.html
{% load static %}
{% load humanize %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- FontAswsome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP"
    crossorigin="anonymous">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
    crossorigin="anonymous">

  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/nav.css' %}">

  <title>{% block title %}CC Gains{% endblock %}</title>
</head>

<body>
  <div class="container-fluid p-2">
    <div class="row">
      <div class="col-5 col-md-4 small">
        Market Cap: ${{market_cap.market_cap|intcomma}}
      </div>
      <div class="col-md-3 d-none d-md-block small">
        24h Volume: ${{market_cap.24h_volume|intcomma}}
      </div>
      <div class="col-7 col-md-5 small">
        Change (1h): {{market_cap.change.1h}}%   (24h): {{market_cap.change.24h}}%   (7d): {{market_cap.change.7d}}%
      </div>

    </div>
  </div>

  <nav class="navbar navbar-expand-sm navbar-custom border-top border-bottom sticky-top" style="border-color: #F8F9FA;">

    <a class="navbar-brand" style="margin-left: 10px;"><i class="fab fa-bitcoin"></i>CC Gains</a>

    <button class="navbar-toggler " data-toggle="collapse" data-target="#navbarcollapse">
      <i class="fa fa-bars fa-lg"></i>
    </button>

    <div class="collapse navbar-collapse justify-content-sm-end " id="navbarcollapse">

      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'crypto:index' %}">Charts</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <main>
    <div class="container-fluid my-4">
      <div class="row">
        <div class="col-10 col-md-8 col-lg-7 align-items-stretch mx-auto">
          <div class="card">
            <img class="card-img-top" src="{% static 'img/card1.jpg' %}">
            <div class="card-body">
              <p class="card-text">
                {% block content %}
                {% endblock %}</p>
            </div>
          </div>
        </div>
      </div>
  </main>


  <hr class="my-2">
  <div class="jumbotron jumbotron-fluid" style="margin-bottom: 0px;">
    <div class="container-fluid padding">
      <div class="row text-center padding">
        <div class="col-12 pb-2">
          <h2 class="display-4">Social Media</h2>
        </div>
        <div class="col-12 social">
          <a href="https://www.plus.google.com" target="_blank"><i class="fab fa-google-plus-g fa-lg"></i></a>
          <a href="https://github.com" target="_blank"><i class="fab fa-github fa-lg"></i> </a>
          <a href="https://www.twitter.com" target="_blank"><i class="fab fa-twitter fa-lg"></i> </a>
          <a href="https://www.facebook.com" target="_blank"><i class="fab fa-facebook fa-lg "></i> </a>
        </div>
      </div>
    </div>
    </footer>

    <script src="https://code.jquery.com/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
      crossorigin="anonymous"></script>
</body>

</html>

ccgains_project/crypto/templates/crypto/detail.html
{% load static %}
{% load humanize %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- FontAswsome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP"
        crossorigin="anonymous">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
        crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">

    <title>CC_Gains</title>
</head>

<body>
    <div class="container-fluid p-2">
        <div class="row">
            <div class="col-5 col-md-4 small">
                Market Cap: ${{market_cap.market_cap|intcomma}}
            </div>
            <div class="col-md-3 d-none d-md-block small">
                24h Volume: ${{market_cap.24h_volume|intcomma}}
            </div>
            <div class="col-7 col-md-5 small">
                Change (1h): {{market_cap.change.1h}}%   (24h): {{market_cap.change.24h}}%   (7d): {{market_cap.change.7d}}%
            </div>
        </div>
    </div>

    <nav class="navbar navbar-expand-sm navbar-custom border-top border-bottom sticky-top" style="border-color: #F8F9FA;">

        <a class="navbar-brand" style="margin-left: 10px;"><i class="fab fa-bitcoin"></i>CC Gains</a>

        <button class="navbar-toggler " data-toggle="collapse" data-target="#navbarcollapse">
            <i class="fa fa-bars fa-lg"></i>
        </button>

        <div class="collapse navbar-collapse justify-content-sm-end" id="navbarcollapse">

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'crypto:index' %}">Charts</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <section class="section mt-5">
        <div class="container">
            <div class="row">
                <div class="col-6 text-center">
                    <div>
                        <img class="rounded float-left img-thumbnail" src="{{coin_logo}}" />
                    </div>
                </div>
                <div class="col-6 text-center">
                    <div>
                        <h2 class="display-4 text-left">{{coin_symbol}}</h2>
                        <ul class="list-group">
                            <li class="list-group-item">Change (1h): {{coin_stats.change.hour}}%</li>
                            <li class="list-group-item">Change (24h): {{coin_stats.change.day}}%</li>
                            <li class="list-group-item">Current Price: ${{coin_stats.price|floatformat:2|intcomma}}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <hr class="my-4">

    {% if user.is_authenticated %}
    <div class="container-fluid padding">
        <div class="row welcome text-center">
            <div class="col-12">
                <h1 class="display-4 bold">Personal coins</h1>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col">
                {% if user_coins %}
                <ul class="list-group">
                    {% for coin in user_coins %}
                    <li class="list-group-item">
                        Amount: {{coin.amount|intcomma}} x ${{coin.price|floatformat:2|intcomma}}
                        <div class="text-right">
                            <a href="{% url 'crypto:detail_edit' coin_symbol=coin_symbol coin_id=coin.id %}" class="btn btn-outline-secondary">EDIT</a>
                            <a href="{% url 'crypto:detail_delete' coin_symbol=coin_symbol coin_id=coin.id %}" class="btn btn-outline-secondary">DELETE</a>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    <hr class="my-4">

    <div class="container padding">
        <div class="row welcome text-center">
            <div class="col-12">
                <h2 class="lead">Statistics</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-6 text-left">
                <ul class="list-group">
                    <li class="list-group-item">Total sum starting: ${{sum_value|floatformat:2|intcomma}}</li>
                    <li class="list-group-item">Total sum current: ${{sum_value_current|floatformat:2|intcomma}}</li>
                    <li class="list-group-item">All-time high sum: ${{sum_ath|floatformat:2|intcomma}}</li>
                    <li class="list-group-item">Sum monthly high: ${{sum_month_h|floatformat:2|intcomma}}
                    <li class="list-group-item">Sum monthly low: ${{sum_month_l|floatformat:2|intcomma}}</li>
                </ul>
            </div>
        </div>
    </div>

    <hr class="my-5">


    {% else %}
    <div class="container-fluid padding">
        <div class="row welcome text-center">
            <div class="col-12">
                <p class="lead">User doesn't have this coin</p>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="container">
        <div class="row welcome text-center">
            <div class="col-12">
                <h2 class="lead">Add coins</h2>
            </div>
        </div>
        <div class=row>
            <div class="col-7 mx-auto">
                <div class="card text-center" style="min-width: width 238px;">
                    <div class="card-body">
                        <form method="POST" class="coinform">
                            {% csrf_token %}
                            {{form.as_p}}
                            <button type="submit" class="save btn btn-outline-secondary">Save</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    <hr class="my-4">

    <div class="jumbotron jumbotron-fluid" style="margin-bottom: 0px;">
        <div class="container-fluid padding">
            <div class="row text-center padding">
                <div class="col-12 pb-2">
                    <h2 class="display-4">Social Media</h2>
                </div>
                <div class="col-12 social">
                    <a href="https://www.plus.google.com" target="_blank"><i class="fab fa-google-plus-g fa-lg"></i></a>
                    <a href="https://github.com" target="_blank"><i class="fab fa-github fa-lg"></i> </a>
                    <a href="https://www.twitter.com" target="_blank"><i class="fab fa-twitter fa-lg"></i> </a>
                    <a href="https://www.facebook.com" target="_blank"><i class="fab fa-facebook fa-lg"></i>
                    </a>
                </div>
            </div>
        </div>
        </footer>

        <script src="https://code.jquery.com/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>
</body>

</html>

ccgains_project/crypto/templates/crypto/detail_delete.html
{% load static %}
{% load humanize %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- FontAswsome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP"
        crossorigin="anonymous">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
        crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">

    <title>CC_Gains</title>
</head>

<body>
    <div class="container-fluid p-2">
        <div class="row">
            <div class="col-5 col-md-4 small">
                Market Cap: ${{market_cap.market_cap|intcomma}}
            </div>
            <div class="col-md-3 d-none d-md-block small">
                24h Volume: ${{market_cap.24h_volume|intcomma}}
            </div>
            <div class="col-7 col-md-5 small">
                Change (1h): {{market_cap.change.1h}}%   (24h): {{market_cap.change.24h}}%   (7d): {{market_cap.change.7d}}%
            </div>

        </div>
    </div>

    <nav class="navbar navbar-expand-sm navbar-custom border-top border-bottom sticky-top" style="border-color: #F8F9FA;">

        <a class="navbar-brand" style="margin-left: 10px;"><i class="fab fa-bitcoin"></i>CC Gains</a>

        <button class="navbar-toggler " data-toggle="collapse" data-target="#navbarcollapse">
            <i class="fa fa-bars fa-lg"></i>
        </button>

        <div class="collapse navbar-collapse justify-content-sm-end" id="navbarcollapse">

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'crypto:index' %}">Charts</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <section class="section mt-5">
        <div class="container">
            <div class="row">
                <div class="col-6 text-center">
                    <div>
                        <img class="rounded float-left img-thumbnail" src="{{coin_logo}}" />
                    </div>
                </div>
                <div class="col-6 text-center">
                    <div>
                        <h2 class="display-4 text-left">{{coin_symbol}}</h2>
                        <ul class="list-group">
                            <li class="list-group-item">Change (1h): {{coin_stats.change.hour}}%</li>
                            <li class="list-group-item">Change (24h): {{coin_stats.change.day}}%</li>
                            <li class="list-group-item">Current Price: ${{coin_stats.price|floatformat:2|intcomma}}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <hr class="my-4">

    <div class="container">
        <div class="row welcome text-center">
            <div class="col-12">
                <h3 class="lead">Delete Coin</h3>
                <h2 class="lead">Are you sure you want to delete {{user_coins.amount|intcomma}} x ${{user_coins.price|floatformat:2|intcomma}}?</h2>
            </div>
        </div>
        <div class=row>
            <div class="col-7 mx-auto">
                <div class="card text-center" style="min-width: width 238px;">
                    <div class="card-body">
                        <form method="POST" action="">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-secondary">Yes</button>
                            <a href="{% url 'crypto:detail' coin_symbol=coin_symbol %}" class="btn btn-outline-secondary">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr class="my-4">

    <div class="jumbotron jumbotron-fluid" style="margin-bottom: 0px;">
        <div class="container-fluid padding">
            <div class="row text-center padding">
                <div class="col-12 pb-2">
                    <h2 class="display-4">Social Media</h2>
                </div>
                <div class="col-12 social">
                    <a href="https://www.plus.google.com" target="_blank"><i class="fab fa-google-plus-g fa-lg"></i></a>
                    <a href="https://github.com" target="_blank"><i class="fab fa-github fa-lg"></i> </a>
                    <a href="https://www.twitter.com" target="_blank"><i class="fab fa-twitter fa-lg"></i> </a>
                    <a href="https://www.facebook.com" target="_blank"><i class="fab fa-facebook fa-lg"></i>
                    </a>
                </div>
            </div>
        </div>
        </footer>

        <script src="https://code.jquery.com/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>
</body>

</html>
>>>>>>> f4b9680b85a2c21d7d8d7469d07e3233f1d3b9fb

ccgains_project/crypto/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<h2 class="display-4">Welcome {{ user.username }}!</h2>
  <a href="{% url 'logout' %}" class="btn btn-outline-secondary">logout</a>
{% else %}
<h4><i class="fas fa-spinner fa-pulse m-2"></i>You are not logged in<i class="fas fa-spinner fa-pulse m-2"></i></h4>
<br>
  <a href="{% url 'login' %}" class="btn btn-outline-secondary">Login</a>
  <a href="{% url 'crypto:signup' %}" class="btn btn-outline-secondary">Signup</a>
{% endif %}
{% endblock %}

ccgains_project/crypto/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button class="btn btn-outline-secondary" type="submit">Sign up</button>
</form>
{% endblock %}